#!/usr/bin/expect -f
# Usage: ./centmin-ssh.exp originalport newport

set originalport [lindex $argv 0]
set newport [lindex $argv 1]
 
# Makes it so that expect does not time out
set timeout -1
 
# Run the Centmin install
spawn "./centmin.sh"

# Set buffer size
match_max 100000

# Wait for initial prompt
expect "Enter option ? 1 - 21 ?"

# Send the install command
send -- "16\r"

expect ""

send -- "$originalport\r"

expect ""

send -- "$newport\r"
